name: Block Direct Push to test/prod values files

on:
  push:
    branches:
      - main

jobs:
  protect-env-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Block if protected files are modified
        run: |
          echo "Changed files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == "values-test.yaml" || "$file" == "values-prod.yaml" ]]; then
              echo "❌ ERROR: Direct commits to $file are not allowed. Please raise a PR for review."
              exit 1
            fi
          done
