name: block-prod-push

on:
  push:
    branches: [ main ]

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v44
      - name: Block test/prod files
        run: |
          for file in ${{ steps.files.outputs.all_changed_files }}; do
            if [[ "$file" == "values-test.yaml" || "$file" == "values-prod.yaml" ]]; then
              echo "🚫 Direct push to $file blocked. Use PR."
              exit 1
            fi
          done


